using System.IO;
using Microsoft.EntityFrameworkCore;
using PosSystem.Data;
using PosSystem.Data.Repositories;

namespace PosSystem.Services;

// ── Report DTOs ──────────────────────────────────────────────────────────────

// Read-only snapshot of the migration readiness state for the shared pos.db.
// Generated by SharedToTenantMigrationAuditor.AnalyzeAsync; never mutated by
// the auditor itself. Consumers (future Phase 10.4 migrator, operator UI,
// support ticket bundles) treat this as data only.
public sealed class TenantMigrationDryRunReport
{
    public string SourceDbPath        { get; init; } = "";
    public bool   SourceDbExists      { get; init; }

    // True when the path provider is still in its default legacy mode — i.e.
    // the shared pos.db is what the running app currently uses. A migration
    // makes sense only while this is true.
    public bool   ProviderIsLegacy    { get; init; }

    // The tenant the login screen would prefill, sourced from
    // global_settings.json. Drives the "best-guess owner" rule for untagged
    // legacy sales when the migrator runs.
    public string? LastTenantSubdomain { get; init; }

    // The current session's tenant, sourced from the in-DB Settings table.
    public string? CurrentSessionSubdomain { get; init; }

    public System.Collections.Generic.IReadOnlyList<TenantMigrationSummary> Tenants
        { get; init; } = System.Array.Empty<TenantMigrationSummary>();

    // Sales rows with empty TenantSubdomain — predate Phase 0.5 tagging.
    // Migrator policy will decide whether to attach them to LastTenantSubdomain
    // or quarantine.
    public int    UntaggedSalesCount  { get; init; }
    public decimal UntaggedSalesTotalAmount { get; init; }
    public int    UntaggedPendingCount { get; init; }

    // Settings keys with a `:<tenant>` suffix (bootstrap_completed_at:<t>,
    // last_*_sync_at:<t>, last_stock_reconcile_at:<t>). The migrator will
    // strip the suffix and write the value into each tenant's own DB.
    public System.Collections.Generic.IReadOnlyList<string> TenantSuffixedSettingKeys
        { get; init; } = System.Array.Empty<string>();

    // Human-readable observations + warnings the operator should see before
    // approving the migration.
    public System.Collections.Generic.IReadOnlyList<string> Observations
        { get; init; } = System.Array.Empty<string>();

    public System.DateTime GeneratedAtUtc { get; init; } = System.DateTime.UtcNow;
}

public sealed class TenantMigrationSummary
{
    public string Subdomain            { get; init; } = "";
    public string TargetDbPath         { get; init; } = "";

    public int    TotalSales           { get; init; }
    public int    SyncedSales          { get; init; }
    public int    PendingSales         { get; init; }   // unsynced & !poison
    public int    PoisonSales          { get; init; }   // unsynced & poison
    public int    FailedSales          { get; init; }   // unsynced & LastSyncError != ''
    public decimal PendingTotalAmount  { get; init; }

    public bool   HasBootstrapMarker   { get; init; }
    public bool   HasProductWatermark  { get; init; }
    public bool   HasCustomerWatermark { get; init; }
    public bool   HasStockReconcileMarker { get; init; }

    public bool   IsCurrentSession     { get; init; }
    public bool   IsLastUsedGlobal     { get; init; }
}

// ── Auditor ──────────────────────────────────────────────────────────────────

// Read-only dry-run auditor for the per-tenant DB partitioning migration. Does
// NOT move data, NOT create tenant DB files, NOT modify the shared pos.db, NOT
// touch the path provider. Safe to instantiate, safe to call manually.
//
// Phase 10.4A introduces this service in DI; Phase 10.4B will consume the
// report to drive the actual migrator.
public sealed class SharedToTenantMigrationAuditor
{
    private readonly IDbContextFactory<AppDbContext> _dbFactory;
    private readonly ILocalDatabasePathProvider      _pathProvider;
    private readonly GlobalSettingsRepository        _global;
    private readonly SettingsRepository              _settings;

    public SharedToTenantMigrationAuditor(
        IDbContextFactory<AppDbContext> dbFactory,
        ILocalDatabasePathProvider pathProvider,
        GlobalSettingsRepository global,
        SettingsRepository settings)
    {
        _dbFactory    = dbFactory;
        _pathProvider = pathProvider;
        _global       = global;
        _settings     = settings;
    }

    public async System.Threading.Tasks.Task<TenantMigrationDryRunReport> AnalyzeAsync(
        System.Threading.CancellationToken ct = default)
    {
        var sourcePath = _pathProvider.GetLegacyDbPath();
        var sourceExists = File.Exists(sourcePath);
        var providerIsLegacy = !_pathProvider.IsTenantScoped;
        var lastUsedGlobal = _global.Get("last_tenant_subdomain");
        var observations = new System.Collections.Generic.List<string>();

        if (!sourceExists)
        {
            observations.Add("Legacy pos.db is absent — nothing to migrate.");
            return new TenantMigrationDryRunReport
            {
                SourceDbPath = sourcePath,
                SourceDbExists = false,
                ProviderIsLegacy = providerIsLegacy,
                LastTenantSubdomain = lastUsedGlobal,
                Observations = observations,
            };
        }

        using var db = _dbFactory.CreateDbContext();

        // Per-tenant aggregates in a single GROUP BY round-trip.
        var groups = await db.Sales
            .Where(s => s.TenantSubdomain != "")
            .GroupBy(s => s.TenantSubdomain)
            .Select(g => new
            {
                Subdomain    = g.Key,
                Total        = g.Count(),
                Synced       = g.Count(s => s.Synced),
                Pending      = g.Count(s => !s.Synced && !s.IsPoison),
                Poison       = g.Count(s => !s.Synced && s.IsPoison),
                Failed       = g.Count(s => !s.Synced && s.LastSyncError != ""),
                PendingTotal = g.Where(s => !s.Synced).Sum(s => (decimal?)s.TotalAmount) ?? 0m,
            })
            .ToListAsync(ct);

        // Settings keys + tenants surfaced via key suffixes.
        var settingKeys = await db.Settings.Select(s => s.Key).ToListAsync(ct);

        var tenantSet = new System.Collections.Generic.HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var g in groups) tenantSet.Add(g.Subdomain);

        var tenantSuffixedKeys = new System.Collections.Generic.List<string>();
        foreach (var key in settingKeys)
        {
            var idx = key.LastIndexOf(':');
            if (idx <= 0 || idx >= key.Length - 1) continue;

            // Heuristic: keys we know are tenant-suffixed.
            var prefix = key.Substring(0, idx);
            if (prefix is "bootstrap_completed_at"
                       or "last_product_sync_at"
                       or "last_customer_sync_at"
                       or "last_stock_reconcile_at")
            {
                tenantSuffixedKeys.Add(key);
                tenantSet.Add(key.Substring(idx + 1));
            }
        }

        var currentSession = _settings.Get("tenant_subdomain");
        if (!string.IsNullOrEmpty(currentSession)) tenantSet.Add(currentSession);
        if (!string.IsNullOrEmpty(lastUsedGlobal)) tenantSet.Add(lastUsedGlobal);

        var groupBySub = groups.ToDictionary(g => g.Subdomain, System.StringComparer.OrdinalIgnoreCase);
        var keySet = new System.Collections.Generic.HashSet<string>(settingKeys, System.StringComparer.Ordinal);

        var summaries = new System.Collections.Generic.List<TenantMigrationSummary>();
        foreach (var t in tenantSet.OrderBy(x => x, System.StringComparer.OrdinalIgnoreCase))
        {
            groupBySub.TryGetValue(t, out var g);
            summaries.Add(new TenantMigrationSummary
            {
                Subdomain               = t,
                TargetDbPath            = _pathProvider.GetTenantDbPath(t),
                TotalSales              = g?.Total       ?? 0,
                SyncedSales             = g?.Synced      ?? 0,
                PendingSales            = g?.Pending     ?? 0,
                PoisonSales             = g?.Poison      ?? 0,
                FailedSales             = g?.Failed      ?? 0,
                PendingTotalAmount      = g?.PendingTotal ?? 0m,
                HasBootstrapMarker      = keySet.Contains($"bootstrap_completed_at:{t}"),
                HasProductWatermark     = keySet.Contains($"last_product_sync_at:{t}"),
                HasCustomerWatermark    = keySet.Contains($"last_customer_sync_at:{t}"),
                HasStockReconcileMarker = keySet.Contains($"last_stock_reconcile_at:{t}"),
                IsCurrentSession        = string.Equals(t, currentSession, System.StringComparison.OrdinalIgnoreCase),
                IsLastUsedGlobal        = string.Equals(t, lastUsedGlobal, System.StringComparison.OrdinalIgnoreCase),
            });
        }

        var untaggedCount   = await db.Sales.CountAsync(s => s.TenantSubdomain == "", ct);
        var untaggedTotal   = await db.Sales.Where(s => s.TenantSubdomain == "")
            .SumAsync(s => (decimal?)s.TotalAmount, ct) ?? 0m;
        var untaggedPending = await db.Sales.CountAsync(s => s.TenantSubdomain == "" && !s.Synced, ct);

        // Observations / warnings the operator should see.
        if (summaries.Count == 0 && untaggedCount == 0)
            observations.Add("Shared pos.db has no tenant data — migration is a no-op.");

        if (untaggedCount > 0)
        {
            observations.Add(
                $"{untaggedCount} sales lack a TenantSubdomain (predate Phase 0.5). " +
                $"Migrator policy will route them to LastTenantSubdomain or quarantine.");
            if (untaggedPending > 0)
                observations.Add(
                    $"{untaggedPending} of those untagged sales are still pending — losing them would lose money.");
        }

        foreach (var s in summaries)
        {
            if (s.PoisonSales > 0)
                observations.Add(
                    $"Tenant '{s.Subdomain}': {s.PoisonSales} poison sales will move alongside the pending queue.");
            if (s.HasBootstrapMarker && s.TotalSales == 0)
                observations.Add(
                    $"Tenant '{s.Subdomain}': bootstrap marker exists but no sales — its target DB will start empty.");
        }

        if (summaries.Count > 1)
            observations.Add(
                $"{summaries.Count} tenants detected — catalog (Products/Customers/PriceLists/ProductTypes) " +
                "in the shared DB belongs only to the last-used tenant under the pre-Phase-10 wipe-on-logout " +
                "contract. Other tenants' target DBs will start with empty catalogs and re-bootstrap on first login.");

        if (!providerIsLegacy)
            observations.Add("Provider is in tenant mode — auditor inspected the tenant DB, not the shared pos.db.");

        return new TenantMigrationDryRunReport
        {
            SourceDbPath              = sourcePath,
            SourceDbExists            = true,
            ProviderIsLegacy          = providerIsLegacy,
            LastTenantSubdomain       = lastUsedGlobal,
            CurrentSessionSubdomain   = currentSession,
            Tenants                   = summaries,
            UntaggedSalesCount        = untaggedCount,
            UntaggedSalesTotalAmount  = untaggedTotal,
            UntaggedPendingCount      = untaggedPending,
            TenantSuffixedSettingKeys = tenantSuffixedKeys,
            Observations              = observations,
        };
    }
}
